### ISSUE TITLE
Repository initialization missing environment variables

### ISSUE THREAD

**Issue by wttw** [paulfantom/ansible-restic#21]
In configure.yml/Initialize restic repositories the environment variables needed to authenticate with, e.g., backblaze aren't set, so it fails with an error like "Fatal: create repository at b2:wttw-whatever:/wherever failed: Fatal: unable to open B2 backend: Account ID ($B2_ACCOUNT_ID) is empty".

I'm guessing it needs the remote_credentials passed in, much as they are in restic.cron.j2.

I've worked around it here, but I'm not quite fluent enough in ansible to do it the right way.

**Comment by maloddon** [comment]
Hi, 

I ran into the same issue here. Fixed it quickly with something like 

```
 environment: "{{ item.remote_credentials | d({}) | combine({'RESTIC_PASSWORD': item.password}) }}"
```

in the corresponding init task in `configure.yml` playbook. This is not optimal yet, because `item.remote_credentials` have to be filtered with `| uppercase` filter. I will look to make a proper fix and submit it in a pull request as soon as I have some free time.
